# Railway.toml - NestJS 프로젝트 배포 설정
# 참조: https://backboard.railway.app/railway.schema.json

[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"
watchPatterns = [
  "src/**/*.ts",
  "package.json",
  "package-lock.json",
  "tsconfig.json",
  "nest-cli.json"
]

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/v1/users"
healthcheckTimeout = 30
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# 리소스 제한 설정
[deploy.limitOverride]
[deploy.limitOverride.containers]
cpu = 1.0                    # 1 vCPU
memoryBytes = 1073741824     # 1GB RAM (1024 * 1024 * 1024)
diskBytes = 2147483648       # 2GB 디스크 (2 * 1024 * 1024 * 1024)

# develop 환경 설정 (develop 브랜치용)
# develop 브랜치를 develop 환경으로 사용

# 프로덕션 환경 설정
[environments.production]
[environments.production.build]
builder = "NIXPACKS"
buildCommand = "npm ci --only=production && npm run build"
buildEnvironment = "V2"

[environments.production.deploy]
startCommand = "npm run deploy:prod:safe"
healthcheckPath = "/api/v1/users"
healthcheckTimeout = 45      # 마이그레이션 시간 고려하여 증가
numReplicas = 2              # 프로덕션에서는 2개 인스턴스
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
overlapSeconds = 30          # 무중단 배포를 위한 겹침 시간
drainingSeconds = 30         # Graceful shutdown 시간
rollbackOnHealthcheckFailure = true  # 헬스체크 실패 시 자동 롤백
maxHealthcheckFailures = 2   # 3회 연속 실패 시 롤백 트리거

# 프로덕션 리소스 제한 (더 높게)
[environments.production.deploy.limitOverride]
[environments.production.deploy.limitOverride.containers]
cpu = 2.0                    # 2 vCPU
memoryBytes = 2147483648     # 2GB RAM
diskBytes = 5368709120       # 5GB 디스크

# develop 환경 설정 (develop 브랜치)
[environments.staging]
[environments.staging.build]
buildCommand = "npm ci && npm run build"

[environments.staging.deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/v1/users"
healthcheckTimeout = 30
numReplicas = 1
sleepApplication = true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
rollbackOnHealthcheckFailure = true  # 헬스체크 실패 시 자동 롤백
maxHealthcheckFailures = 2   # develop 환경은 2회 실패 시 롤백 (더 빠른 감지)

[environments.staging.deploy.limitOverride]
[environments.staging.deploy.limitOverride.containers]
cpu = 1.0
memoryBytes = 1073741824     # 1GB RAM
diskBytes = 2147483648       # 2GB 디스크 